twig:
    paths: ['%kernel.project_dir%/templates']
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_theme:
      #- "bootstrap_4_horizontal_layout.html.twig"
      - "component/form_field.html.twig"
      #- "bootstrap_4_layout.html.twig"

    globals:
      template_helper: '@App\Service\BaseTemplateHelper'
      layout: '%layout%'
      menu_style: '%menu_style%'
