<?php
/**
 * Created by PhpStorm.
 * User: ypoon
 * Date: 3/9/2018
 * Time: 6:05 PM
 */

namespace App\FormType\Form\Appraisal\Version1;

use App\FormType\Component\CompositeCollectionType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class FormMainType extends AbstractType {
	public function buildForm(FormBuilderInterface $builder, array $options) {
		$builder->add("staff_name", TextType::class)
			->add("staff_department", TextType::class)
			->add("staff_position", TextType::class)
			->add("staff_office", TextType::class)
			->add("survey_period", TextType::class)
			->add("appraiser_name", TextType::class)
			->add("countersigner_name", TextType::class)
			->add("survey_commencement_date", TextType::class)
			->add("part_a", CompositeCollectionType::class, [
				"entry_type" => PartAType::class,
				"label" => false,
				"force_serial_index" => true
			])
			->add("part_a_overall_score", TextType::class)
			->add("countersigner_1_name", TextType::class)
			->add("countersigner_2_name", TextType::class)
			->add("countersigner_1_part_a_score", TextType::class)
			->add("countersigner_2_part_a_score", TextType::class)
			->add("part_b1", CollectionType::class, [
				"entry_type" => PartBType::class,
				"label" => false,
				"entry_options" => [
					"lhs_text" => [
						"a",
						"b",
						"c",
						"d",
						"e"
					],
				],

			])
			->add("part_a_total", TextType::class)
			;
	}

	public function configureOptions(OptionsResolver $resolver) {
		parent::configureOptions($resolver); // TODO: Change the autogenerated stub
	}

	public function getBlockPrefix() {
		return "version_1_main";
	}
}