<?php
/**
 * Created by PhpStorm.
 * User: ypoon
 * Date: 4/9/2018
 * Time: 3:03 PM
 */

namespace App\FormType\Form\Appraisal\Version1;


use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\FormInterface;
use Symfony\Component\Form\FormView;
use Symfony\Component\OptionsResolver\OptionsResolver;

class PartB2Type extends AbstractType {
	public function buildForm(FormBuilderInterface $builder, array $options) {
		parent::buildForm($builder, $options); // TODO: Change the autogenerated stub
		$builder->add("self_score", NumberType::class)
			->add("self_example", TextareaType::class)
			->add("appraiser_score", NumberType::class)
			->add("appraiser_example", TextareaType::class);
	}

	public function buildView(FormView $view, FormInterface $form, array $options) {
		parent::buildView($view, $form, $options); // TODO: Change the autogenerated stub
		$view->vars["title"] = [
			"Influence, Negotiation and Persuasion",
			"Coaching and Developing",
			"Leadership and Strategic Thinking"
		];
		$view->vars["lhs_text"] = [
			"0" => [
				"5. Effective influencer and persuader at all levels, able to get most ideas accepted in diverse groups at most levels of seniority.",
				"4. Inspires confidence, has credibility with colleagues and customers and is able to get complex ideas accepted. It is generally able to persuade from a basis of openness and clarity.",
				"3. Make a positive impact, is clear, concise, articulate and assertive when providing information and considered logical and reasoned in presenting own case. Able to compromise with customers (or other stakeholder) by convincing them of one's ideas and thoughts from various point of view.",
				"2. Has no involvement in making oral or written presentations or in getting ideas or views across to others. Not able to find acceptable solution for all the parties from mid/long term prospective instead of insisting on one's idea.",
				"1. Colleagues and/or customers pay little attention to debate, proffered solutions or written work. Contributions within team or at meetings are generally not listened to."
			],
			"1" => [
				"5. Takes time to coach and develop people for improved performance; Pro-active in idenitifying and developing high calibrae knowledge, and planning for enhancement of managerial qualities in self and others.",
				"4. Provides regular feedback on performance, suggests improvements, listens and empathises with others, and gets people to commit to responsibilties and try new techniques; Pro-active in sharing knowledge, leading, training, supporting and motivating people to achieve results and improve their works.",
				"3. Translates performance targets into clear objectives. Generally coaches and supports others on low level daily issues.",
				"2. Is not involved in coaching and developing others.",
				"1. Hinders the development of others and generally provides no or negative feedback. Unwilling to devote time to development of others."
			],
			"2" => [
				"5. Become a role model in upholding the Company philosophy. Has a record of leading teams achieving results in difficult situations and creates a climate where employees are highly motivated to achieve goals.",
				"4. Become a role model in upholding the Company philosophy. Has a record of clear motivational leadership, recognition of other's achievements and development of visions, targets and techniques which have kept teams and/or individuals focused on the goals. Has introduced and managed change initiatives in own team effectively.",
				"3. Able to set a good example in terms of diligency, integrity and ethically. Has record of achieving results through others when asked, or opportunities arise. Has explained to subordinates the Company values, goal and team quality objectives for their understanding and support.",
				"2. Failed to set any good example in terms of diligency, integrity and ethically. Has not had the opportunity to demonstrate leadership qualities or shared the quality objectives with subordinates.",
				"1. Set many bad examples in terms of diligency, integrity and ethically. Unable to lead teams, does not provide direct and lowers morale."
			]
		];
	}


	public function configureOptions(OptionsResolver $resolver) {
		$resolver->setDefaults([
			"label" => false,
		]);
		parent::configureOptions($resolver);
	}

	public function getBlockPrefix() {
		return "version_1_b2";
	}


}