<?php
/**
 * Created by PhpStorm.
 * User: ypoon
 * Date: 4/9/2018
 * Time: 3:03 PM
 */

namespace App\FormType\Form\Appraisal\Version1;


use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\FormInterface;
use Symfony\Component\Form\FormView;
use Symfony\Component\OptionsResolver\OptionsResolver;

class PartB1Type extends AbstractType {
	public function buildForm(FormBuilderInterface $builder, array $options) {
		parent::buildForm($builder, $options); // TODO: Change the autogenerated stub
		$builder->add("self_score", NumberType::class)
			->add("self_example", TextareaType::class)
			->add("appraiser_score", NumberType::class)
			->add("appraiser_example", TextareaType::class);
	}

	public function buildView(FormView $view, FormInterface $form, array $options) {
		parent::buildView($view, $form, $options); // TODO: Change the autogenerated stub
		$view->vars["title"] = [
			"Teamwork and Support",
			"Ownership",
			"Customer Focus",
			"Initiative",
			"Attention to Detail",
			"Problem Solving and Decision Making",
			"Achieving Results and Compliance",
			"Communication and Interpersonal",
		];
		$view->vars["lhs_text"] = [
			"0" => [
				"5. Fosters team spirit, encourages others to contribute and draws on wide variety of others' skills to achieve team success.",
				"4. Cooperates with colleagues, willingly shares team values, listens, makes a constructive contribution to teams and builds on team success.",
				"3. Liaises with colleagues, willingly shares team information and knowledge and makes a constructive contribution to teams. Recognize one's limit and seek for support without delay.",
				"2. Did not demonstrate the willingness to work amicably with colleagues or proactively support others in times of need.",
				"1. Behaves in a disruptive manner within team, is confrontational and negatively criticises others and their contributions. Not considered a team worker."
			],
			"1" => [
				"5. Has a record of taking ownership for major problems, crises and issues and ensuring timely and well judged decisions are made and involving others as necessary.",
				"4. Has a record of taking ownership for customer problems, team goals and challenging objectives and seeks assistance whenever appropriate.",
				"3. Has a limited record of taking ownership for own decisions and outcomes and does not depend unduly on others, however, knows when to ask for assistance.",
				"2. Has not demonstrated ownership.",
				"1. Ignores potential problems, 'not my problem attitude', blames others for problems rather than helps to resolve problems."
			],
			"2" => [
				"5. Exceeds customers' expectations, develops mutually beneficial relationships with customers.",
				"4. Has an in-depth understanding of customer needs (gained via experience and research), use this build customer confidence, to develop improvements in customer service levels and relationships.",
				"3. Has correct understanding of customer needs, received good customer feedback, responding appropriately to customer issues and displays a concern to improve customer service levels.",
				"2. Has no record of working with internal or external customers.",
				"1. Has no observable desire to provide service to others. Past customers have requested that this person does no further work/is removed from site."
			],
			"3" => [
				"5. Has a record of creating, seizing and driving new ideas and opportunities to implementation.",
				"4. Anticipates problems and takes preemptive action to deal with them, has a record of evaluating problems and developing more effective ways of doing things.",
				"3. Gets on with jobs, does not need asking to do things and generates ideas for helping to resolve issues.",
				"2. No evidence of using initiative and seizing opportunities to take action.",
				"1. Shows no initiative at all, has to be asked to do things and requires supervision and guidance or set procedures to follow."
			],
			"4" => [
				"5. Consistently high standard with work right first time, sets an example to others and source of advice and guidance.",
				"4. Shows concern for quality, produces high quality work which is mostly right first time.",
				"3. Concentrates, checks that work is accurate, make few mistakes and learns from them. Seeks advice/help as appropriate.",
				"2. No evidence of concern for quality of the job.",
				"1. Makes careless and simple mistakes, work in generally sloppy and has to be checked or re-worked, shows no concern for quality standards. Mistakes have impact on service quality."
			],
			"5" => [
				"5. Has record of developing timely solutions for major problems, looks at wider issues, is creative and uses wide range of tools and sources to develop solutions.",
				"4. Has record of analysing and developing solutions to complex problems, searches widely for options, aware and proficient in a variety of techniques. Offered new ideas and solutions that are not tied to past method and result in order to increase the value of work.",
				"3. Has record of handling straight forward problems and developing workable solutions including but not limited to reorganize work unit structure, job assignment or resources. Offered constructive and practical suggestions to tackle work problems.",
				"2. No evidence of successful problem solving skills and not willing to handle challenging tasks or accept changes in role or situation.",
				"1. Is generally unsuccessful in solving problems or takes longer than necessary even with straight forward problems. No concept of whom to ask for support/advice and can handle ordinary routine works only."
			],
			"6" => [
				"5. Has a record of achieving nearly all goals set on schedule, in budget, and anticipating and managing complexities, changing priorities and needs - 80/20%, while the tasks completed are complying the Company goals, quality objectives, policies and procedures.",
				"4. Has a record of mostly achieving goals agreed or set in budget and generally on schedule - 70/30%, while the tasks completed are complying the Company goals, quality objectives, policies and procedures.",
				"3. Has a record of generally achieving goals agreed - 60/40%, while the tasks completed are complying the quality objectives, policies and procedures.",
				"2. Not able to demonstrate record of achieving results or more than half of tasks completed are not complying the quality objectives, policies and procedures.",
				"1. Fails to achieve own goals and hinders results of others."
			],
			"7" => [
				"5. Highly articulate, using appropriate language and communication styles at all times, listening and feeding back to show understanding.",
				"4. Listens and appropriately tailors communication approach to suit situation or person. Engages the enthusiastic cooperation and wholehearted participation of others in work tasks and relationships.",
				"3. Regularly reports and updates on progress of responsible task, problems and achievements expected by the supervisors. Communicates clearly and concisely, both verbally and written, ensuring information relayed is accurate, listens to what is being communicated and seeks to understand by solid questioning skills.",
				"2. No evidence of ability to give and receive information with accuracy, cannot explain one's idea and thoughts for acceptance by others.",
				"1. Fails to communicate clearly, struggles to put points across verbally or written"
			],
		];
	}


	public function configureOptions(OptionsResolver $resolver) {
		$resolver->setDefaults([
			"label" => false,
		]);
		parent::configureOptions($resolver);
	}

	public function getBlockPrefix() {
		return "version_1_b1";
	}


}