<?php
/**
 * Created by PhpStorm.
 * User: ypoon
 * Date: 4/9/2018
 * Time: 3:03 PM
 */

namespace App\FormType\Form\Appraisal\Version1;


use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\FormInterface;
use Symfony\Component\Form\FormView;
use Symfony\Component\OptionsResolver\OptionsResolver;

class PartBType extends AbstractType {
	public function buildForm(FormBuilderInterface $builder, array $options) {
		parent::buildForm($builder, $options); // TODO: Change the autogenerated stub
		$builder->add("self_score", NumberType::class)
			->add("self_example", TextareaType::class)
			->add("appraiser_score", NumberType::class)
			->add("appraiser_example", TextareaType::class);
	}

	public function buildView(FormView $view, FormInterface $form, array $options) {
		parent::buildView($view, $form, $options); // TODO: Change the autogenerated stub
		$view->vars["lhs_text"] = $options["lhs_text"];
	}


	public function configureOptions(OptionsResolver $resolver) {
		parent::configureOptions($resolver); // TODO: Change the autogenerated stub
		$resolver->setDefaults([
			"lhs_text" => []
		]);
	}

	public function getBlockPrefix() {
		return "version_1_b";
	}


}