<?php
/**
 * Created by PhpStorm.
 * User: ypoon
 * Date: 5/9/2018
 * Time: 10:54 AM
 */

namespace App\FormType\Form\Appraisal\Version1;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\FormInterface;
use Symfony\Component\Form\FormView;
use Symfony\Component\OptionsResolver\OptionsResolver;

class PartDType extends AbstractType {
	public function buildForm(FormBuilderInterface $builder, array $options) {
		$builder->add("key_respon", TextareaType::class)
			->add("goal_name", TextareaType::class)
			->add("measurement_name", TextareaType::class)
			->add("goal_weight", NumberType::class)
			->add("complete_date", TextType::class)
		;
	}

	public function buildView(FormView $view, FormInterface $form, array $options) {
		parent::buildView($view, $form, $options); // TODO: Change the autogenerated stub
	}

	public function configureOptions(OptionsResolver $resolver) {
		parent::configureOptions($resolver); // TODO: Change the autogenerated stub
	}

	public function getBlockPrefix() {
		return "version_1_d";
	}

}